name: Publish docker image

on:
  push:
    branches: ['master']

jobs:
  build-n-push:
    name: build and push image to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4
      - run: ko publish -B --platform=linux/amd64,linux/arm64 ./
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
